version: 2.1

commands:
  test_common:
    steps:
      - run: curl -L https://bootstrap.saltstack.com | sh -s -- -d -X stable; exit 0
      - run: mkdir -p /etc/salt/minion.d && cp test/minion.d/masterless.conf /etc/salt/minion.d/
      - run: mkdir -p /srv/pillar && cp -r test/pillar /srv/
      - run: mkdir -p /srv/salt && cp -r test/base /srv/salt/
      - run: mkdir -p /srv/salt/base && cp -r datadog /srv/salt/base/
      - run: ls /srv/pillar/
      - run: cat /srv/pillar/datadog.sls
      - run: salt-call --local state.highstate -l debug
  test_ubuntu:
    steps:
      - run: apt-get update && apt-get install -y curl
      - run: cp test/utils/systemctl.py /bin/systemctl
      - run: cp test/utils/systemctl.py /bin/systemd
      - test_common
  test_centos:
    steps:
      - run: yum -y update
      - run: yum install -y curl
      - run: cp test/utils/systemctl.py /usr/bin/systemctl
      - run: cp test/utils/systemctl.py /usr/bin/systemd
      - test_common

  setup_version:
    parameters:
      version:
        type: string
        default: "7"
    steps:
      - run: cp test/pillar/datadog{<<parameters.version>>,}.sls


jobs:
  agent7_ubuntu:
    docker:
      - image: ubuntu:bionic-20191202
    steps:
      - checkout
      - setup_version:
          version: "7"
      - test_ubuntu

  agent7_centos:
    docker:
      - image: centos:7
    steps:
      - checkout
      - setup_version:
          version: "7"
      - test_centos

  agent6_ubuntu:
    docker:
      - image: ubuntu:bionic-20191202
    steps:
      - checkout
      - setup_version:
          version: "6"
      - test_ubuntu

  agent6_centos:
    docker:
      - image: centos:7
    steps:
      - checkout
      - setup_version:
          version: "6"
      - test_centos

  agent5_ubuntu:
    docker:
      - image: ubuntu:bionic-20191202
    steps:
      - checkout
      - setup_version:
          version: "5"
      - test_ubuntu

  agent5_centos:
    docker:
      - image: centos:7
    steps:
      - checkout
      - setup_version:
          version: "5"
      - test_centos


workflows:
  version: 2.1
  test_datadog_formula:
    jobs:
      - agent7_ubuntu
      - agent7_centos
      - agent6_ubuntu
      - agent6_centos
      - agent5_ubuntu
      - agent5_centos
