name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        datadog_version: [ 5, 6, 7 ]
        os: [ debian-9-2019-2-py3, ubuntu-1804-2019-2-py3, centos-7-2019-2-py3 ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build and test with Kitchen
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: "Running tests for ${{ matrix.datadog_version }}-${{ matrix.os }}"
      run: |
        bundle exec kitchen test datadog${{ matrix.datadog_version }}-${{ matrix.os }}
